version: '3.5'

services:
  postgres:
    image: postgres:12
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - gp-postgres:/var/lib/postgresql/data
    networks:
      - gympoint

  redis:
    image: redis:alpine
    container_name: redis
    restart: always
    volumes:
      - gp-redis:/data
    networks:
      - gympoint

  gympoint:
    container_name: gympoint
    build: .
    environment:
      NODE_ENV: ${NODE_ENV}
    volumes:
      - .:/home/node/api
      - /home/node/api/node_modules
    ports:
      - '${APP_PORT}:3333'
    depends_on:
      - postgres
    networks:
      - gympoint


volumes:
  gp-postgres:
    name: gp-postgres
  gp-redis:
    name: gp-redis

networks:
  gympoint:
    name: gympoint
    driver: bridge
